### ISSUE TITLE
There's only one path working in real machines

### ISSUE THREAD

**Issue by Heath68** [qdeconinck/mp-quic#11]
I run MPQUIC on two real machines,but only one path working.I tested on mininet with one network interface ,but there were two pathes.I wonder if there's any solution.Thanks a lot!

**Comment by Heath68** [comment]
Problem solved，it is because of the network interfaces naming problem.

**Comment by 0xVikas** [comment]
@Heath68 can you please tell how you solved this? I am trying to run the example client and server programs but I only see "Path 0" being used .

**Comment by Heath68** [comment]
check your network interfaces‘ names,they can only be named by "eth*" or "wlan*”

**Comment by 0xVikas** [comment]
Can you please help me in making it work with multiple paths in a vm ?

**Comment by qdeconinck** [comment]
If you want to use mp-quic within a VM, why do you not start with the provided VM (https://multipath-quic.org/kvm-mpquic.vmdk.zip) listed in the setup page (https://multipath-quic.org/conext17/2017/12/09/artifacts-available.html)? Normally it should work out-of-the-box.

**Comment by ujjwal-raizada** [comment]
@qdeconinck Can you re-pload the given VM on some different file hosting like gdrive or something? (because I an getting terribly low speed like 2Kbps, and It will take days in that way)

**Comment by Jerry0666** [comment]
@Heath68 Do you know how to set two addrs on it? I renamed the interface name to "eth0" on both the server and client, and only Path 0 is used.
