### ISSUE TITLE
Does MPQUIC not perform full mesh with the client host?

### ISSUE THREAD

**Issue by thomaswpp** [qdeconinck/mp-quic#14]
Does MPQUIC not perform full mesh with the client host? For example, there are two hosts (client and server), each host has two interfaces, in MPTCP there are 4 subflows creating the full mesh, however, in MPQUIC I only see 2 subflows created in the pathmanager. How does MPQUIC work, does it not do full mesh?

**Comment by qdeconinck** [comment]
In our previous experiments, we only considered a server with a single network interface and IP address. It might be possible that the path manager "forgets" to consider the ADD_ADDRESS sent by the server to create new paths on it.

**Comment by thomaswpp** [comment]
Got it. Thanks for the answer.
