### ISSUE TITLE
 AttributeError: 'ExperienceLauncher' object has no attribute 'num'

### ISSUE THREAD

**Issue by BoogalooXiang** [qdeconinck/mp-quic#17]
I followed the instructions and when I started to run the .py file saved in the /minitopo-experiences/experiences files. I got the error:

> AttributeError: 'ExperienceLauncher' object has no attribute 'num'

I used `python quicreqres_test.py`。

I don't know how to fix that. If anyone has met with that problem, could you teach me how to fix that? Thanks in advance: -)

**Comment by Zack-Tsang** [comment]
> I followed the instructions and when I started to run the .py file saved in the /minitopo-experiences/experiences files. I got the error:
> 
> > AttributeError: 'ExperienceLauncher' object has no attribute 'num'
> 
> I used `python quicreqres_test.py`。
> 
> I don't know how to fix that. If anyone has met with that problem, could you teach me how to fix that? Thanks in advance: -)

Hi! Iim running the .py files now! However, I met the connection error, have you tested them before?
