### ISSUE TITLE
ProofInvalid

### ISSUE THREAD

**Issue by BoogalooXiang** [qdeconinck/mp-quic#18]
Hi, I tested
`go run main.go -bind ":8088"` on a terminal and
`go run client/main.go https://localhost:8088` on another terminal
I got the error：
> Closing session with error:ProofInvalid
> Connection fec6298ed2bab059 closed
> panic: Get https://localhost:8088/demo/tiles: ProofInvalid

I have the _id_rsa, id_rsa.pub_ and _authorized_keys_ file in ~/.ssh
I read the README.md, it seems that the privkey.pem and fullchain.pem file in invalid
So I need to get a new privkey.pem and fullchain.pem in example file right? : -)

**Comment by ytxing** [comment]
Hi,
I got the same problem. Do you solve it? How? @BoogalooXiang 

Nice day:)

**Comment by BoogalooXiang** [comment]
Hi, I think you can skip the verification.

Import (
“crypto/tls”
)

hclient := &http.Client{
Transport: &h2quic.RoundTripper{QuicConfig: quicConfig,
TLSClientConfig: &tls.Config{InsecureSkipVerify: true}},   
}

在2020-11-30 19:19:43，ytxingnotifications@github.com写道：

Hi,
I got the same problem. Do you solve it? How? @BoogalooXiang

Nice day:)

**Comment by Zack-Tsang** [comment]
> Hi, I tested `go run main.go -bind ":8088"` on a terminal and `go run client/main.go https://localhost:8088` on another terminal I got the error：
> 
> > Closing session with error:ProofInvalid
> > Connection fec6298ed2bab059 closed
> > panic: Get https://localhost:8088/demo/tiles: ProofInvalid
> 
> I have the _id_rsa, id_rsa.pub_ and _authorized_keys_ file in ~/.ssh I read the README.md, it seems that the privkey.pem and fullchain.pem file in invalid So I need to get a new privkey.pem and fullchain.pem in example file right? : -)

Hi! Have you test the script files provided by Quentin De Coninck in the guide link "https://multipath-quic.org/2017/12/09/artifacts-available.html", like quic_mptcp_https_tests_expdes_wsp_lowbdp_quic.py.
