### ISSUE TITLE
Chrome Integration of MP-QUIC

### ISSUE THREAD

**Issue by adarshdec23** [qdeconinck/mp-quic#2]
I'm interested in integrating MP-QUIC with Chrome so that I can test out the protocols performance with HD video streaming. 
Would this be possible without a lot of changes? 

Thanks, and sorry if this is a vague question.

**Comment by qdeconinck** [comment]
If you want to test Chrome with a mp-quic server, it's likely you need to rebase mp-quic on the current quic-go status branch as mp-quic is based on a (now) old gQUIC version. Also, I think you will need to implement multipath support in Chrome browser (I don't think it is possible to outsource the QUIC process to the go code).

**Comment by adarshdec23** [comment]
Thank you for the confirmation.
