### ISSUE TITLE
Have you realized returning ack frames on different paths？

### ISSUE THREAD

**Issue by JianHaoYu** [qdeconinck/mp-quic#23]
in your paper,I found that you said “it is possible to send ack frame over different paths”.However,I didn't find such packages in my log. Is this function realized?or how can i confirm it？

**Comment by qdeconinck** [comment]
This is because this implementation does not. You may want to have a look at our recent paper (https://hdl.handle.net/2078.1/243486) and the related implementation (https://github.com/p-quic/pquic) that takes advantage of asymmetrical paths by sending ACK frames on different paths.
