### ISSUE TITLE
Client behind  can not receive packets from both of two paths

### ISSUE THREAD

**Issue by cxht** [qdeconinck/mp-quic#26]
I used MPQUIC to transfer files from a server in cloud with one NIC to a client with two NIC, the output log shows that two paths are established but only one path can receive packets. I print the 4 tuple of the two paths from both perspective of client and server, from server's viewpoint, the client addresses are behind NAT(shown in the figure). So the reason of path unable to receive packet is the server can't find the local address of client behind NAT? 
![image](https://user-images.githubusercontent.com/7196400/129033948-fb71c069-9cef-4110-9bcb-b1e218138122.png)

**Comment by nguyenthanhtrungbkhn** [comment]
Hi @cxht , I have the same problem. Looks like you fixed it. Can you tell me in more detail how to configure it? Thank you very much
