### ISSUE TITLE
the aggregated throughput is quite low

### ISSUE THREAD

**Issue by yyLeeShine** [qdeconinck/mp-quic#27]
I have tested your code and find a problem,the client has two ips and the server is one, but when i tested it, lots of udp packets were sent through one ip of the client and a few udp packets were sent through the other ip. so the aggregated output is quite low,Do you test it between the clouds server and your client or you just test it locally ? Have you found this problem?

**Comment by ArthurCChen** [comment]
@yyLeeShine Hi, I've met the same problem when throttling the bandwidth of connections between VMs, did you figure out why and how to solve it?
