### ISSUE TITLE
unable to download mininet VM given in official site https://multipath-quic.org/2017/12/09/artifacts-available.html

### ISSUE THREAD

**Issue by Prakash-Sanchela** [qdeconinck/mp-quic#46]
I was trying to build mp-quic repo and on the official site, mininet vm is already given with all the dependencies installed. I tried to install from the link [http://onlab.vicci.org/mininet-vm/mininet-2.2.1-150420-ubuntu-14.04-server-amd64.zip](https://github.com/quic-go/quic-go/issues/url).

Can someone tell me if the link is still working?

**Comment by qdeconinck** [comment]
The Mininet releases moved to the Release page of the Mininet project on GitHub. The link on the web page now redirects to the official Mininet download page.
