### ISSUE TITLE
Controlling the creation of paths in a real environment - MPQUIC does not create them 

### ISSUE THREAD

**Issue by deliarico** [qdeconinck/mp-quic#50]
Hello,

I am using the MPQUIC implementation extracted from the VM in physical computers. It works in both computers if I use mininet, however, if I want to use it between the two computers it does not create multiple paths and I am not sure why since I am replicating the environment in mininet. 

In mininet, I have a client and a server. The client has this routes:

```
default via 10.0.0.2 dev client-eth0 
10.0.0.0/8 dev client-eth0 proto kernel scope link src 10.0.0.1 
11.0.0.0/8 dev client-eth1 proto kernel scope link src 11.0.0.1
```

The server has this routes:

```
default via 100.0.0.2 dev server-eth0 
100.0.0.0/8 dev server-eth0 proto kernel scope link src 100.0.0.1 
```

I am using a code for sending a file in .go and if I capture the conversation, I see both paths being created (even if one is under used):

 
![Screenshot from 2024-07-19 10-34-00](https://github.com/user-attachments/assets/150c05ba-91fe-4fb0-b91a-bccd666df014)

I am taking the same code but to a real network and now it is not working anymore. I have a client computer with this routes:

```
default via 10.51.0.10 dev enx32cf238b3519 proto dhcp src 10.51.0.9 metric 104 
10.48.0.140/30 dev enx52277ba0b7d5 proto kernel scope link src 10.48.0.142 metric 105 
10.51.0.8/30 dev enx32cf238b3519 proto kernel scope link src 10.51.0.9 metric 104 
```

And a server computer with this routes:

```
default via 10.11.23.1 dev ens160 proto static metric 102 
10.11.23.0/24 dev ens160 proto kernel scope link src 10.11.23.229 metric 102 
```

However, if I use the same server-client code in .go, I only see the creation of one path

![Screenshot from 2024-07-19 10-29-42](https://github.com/user-attachments/assets/6cb8f56b-4a84-41af-8d30-59e5eec17570)

I am not sure why is this happening. I have some assumptions but I am not sure why. I have tried modifing the routes and also having a second ip address in the server but it is not working. I also wonder if there is a way to control the paths in mpquic other than 

```
quicConfig := &quic.Config{
		CreatePaths: true,
}
```

Because I guess than if I can control the creation of paths directly in the code I might fix this...

By the way, I obviously have connectivity from both interfaces of the client to the server:

```
$ ping 10.11.23.229 -I enx32cf238b3519 
PING 10.11.23.229 (10.11.23.229) from 10.51.0.9 enx32cf238b3519: 56(84) bytes of data.
64 bytes from 10.11.23.229: icmp_seq=1 ttl=61 time=15.9 ms
^C
--- 10.11.23.229 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 15.863/15.863/15.863/0.000 ms

$ ping 10.11.23.229 -I enx52277ba0b7d5 
PING 10.11.23.229 (10.11.23.229) from 10.48.0.142 enx52277ba0b7d5: 56(84) bytes of data.
64 bytes from 10.11.23.229: icmp_seq=1 ttl=61 time=16.0 ms
^C
--- 10.11.23.229 ping statistics ---

```

**Comment by deliarico** [comment]
I found the issue... the implementation seems to have hardwired only to use ethernet interfaces named as eth*. I would recommend to add this to the documentation.

**Comment by 7SoumilMukherjee** [comment]
> I found the issue... the implementation seems to have hardwired only to use ethernet interfaces named as eth*. I would recommend to add this to the documentation.

Can you please share exactly which application were you running, since I am facing issues when I am trying to run it on the actual network setup.
