### ISSUE TITLE
How to install MPQUIC in real environment instead of in Mininet

### ISSUE THREAD

**Issue by NotreDameDeParis** [qdeconinck/mp-quic#6]
I want to install MPQUIC in a real environment instead of in Mininet.Has anyone finished installing MPQUIC in a real environment successfully?

**Comment by qdeconinck** [comment]
Our MultipathTester application (https://github.com/multipathtester/MultipathTester) actually bundles MPQUIC which runs in real wireless environments. From a practical viewpoint, you can just follow the VMs instructions related to the Go code only (https://multipath-quic.org/2017/12/09/artifacts-available.html). Then, you can write your QUIC application or example ones and specify actual addresses.

**Comment by NotreDameDeParis** [comment]
Could you please tell me what "Then, you can write your QUIC application or example ones and specify actual addresses." mean?
Do you mean that i can write and run the MPQUIC application in the mininet or just in the real environment instead of Mininet?
If in Mininet, do you mean that i can set the actual addresses in mininet and it is just the same as in the real environment?

**Comment by NotreDameDeParis** [comment]
Can i just directly run this code on two real machines(one as a server and the other as a client) without using Mininet?

**Comment by qdeconinck** [comment]
> Can i just directly run this code on two real machines(one as a server and the other as a client) without using Mininet?

Yes

**Comment by Heath68** [comment]
I  run MPQUIC on two real machines,but only one path working.I tested on mininet with one network interface ,but there were two pathes.I wonder if you solved your problems.Thanks a lot!

**Comment by saptarsi96** [comment]
How to check if mpquic is working or not on my laptop? Do we have any testing websites as mptcp?

**Comment by shravan9912** [comment]
I ran MPQUIC on mininet it worked fine, But when I started running it on real networks it not using two paths. Setup is the following
one machine is a client with two different interfaces and networks, Than another machine is a server with one interface and network. But when I sent a file from the client to the server its using only one network of the client in real-time, But in mininet it was using two networks. can you please help me why the same code of mpquic is not working with real networks?
Thanks in Advance
