### ISSUE TITLE
Which version of quic-go support the existed mpquic

### ISSUE THREAD

**Issue by NotreDameDeParis** [qdeconinck/mp-quic#8]
During the process of installing mpquic, I have met a lot of problems. I found that mpquic was completed around 2 years ago and it has not been updated now, however, quic-go is being continually updated. Could you please tell me which version of quic-go support the existed mpquic?

**Comment by zyx16** [comment]
Do you have any idea now? I also have this problem.

**Comment by qdeconinck** [comment]
quic-go did not merge the multipath proposal. There is still an implementation of Multipath QUIC (with quite different wire format) which is supported as a PQUIC plugin (see https://github.com/p-quic/pquic).
