### ISSUE TITLE
Something wrong with the process

### ISSUE THREAD

**Issue by Heath68** [qdeconinck/mp-quic#9]
Hello,
I followed the tutorial https://multipath-quic.org/2017/12/09/artifacts-available.html
But when I got to `go get -t -u ./...` , there was a problem as belong showing:
```
#github.com/lucas-clemente/quic-go/internal/crypto
internal/crypto/key_derivation.go:47:60: cs.KeyLen undefined (type mint.CipherSuiteParams has no field or method KeyLen)
internal/crypto/key_derivation.go:48:58: cs.IvLen undefined (type mint.CipherSuiteParams has no field or method IvLen)
```
Can you tell me what is the problem is?And I notice there's no reply to lots of issues, is mpquic dead?

**Comment by qdeconinck** [comment]
Did you reset the `mint` repository to the provided commit?
```
$ cd ~/go/src/github.com/bifurcation/mint
$ git reset --hard a6080d464fb57a9330c2124ffb62f3c233e3400e
# Check that no more build issues arise
$ cd ~/go/src/github.com/lucas-clemente/quic-go
$ go build
# This should not produce any output
```

**Comment by Heath68** [comment]
Thanks a lot, this issue got solved.

**Comment by Psylence0609** [comment]
> Did you reset the `mint` repository to the provided commit?
> 
> ```
> $ cd ~/go/src/github.com/bifurcation/mint
> $ git reset --hard a6080d464fb57a9330c2124ffb62f3c233e3400e
> # Check that no more build issues arise
> $ cd ~/go/src/github.com/lucas-clemente/quic-go
> $ go build
> # This should not produce any output
> ```

I have done this but I still get the same error KeyLen and IvLen undefined

**Comment by cat24max** [comment]
> 
> 
> > Did you reset the `mint` repository to the provided commit?
> > ```
> > $ cd ~/go/src/github.com/bifurcation/mint
> > $ git reset --hard a6080d464fb57a9330c2124ffb62f3c233e3400e
> > # Check that no more build issues arise
> > $ cd ~/go/src/github.com/lucas-clemente/quic-go
> > $ go build
> > # This should not produce any output
> > ```
> 
> I have done this but I still get the same error KeyLen and IvLen undefined

Yea you have to reset ALL repos that produce errors. I reset all packages to ~December 2017 and it fixed it.

**Comment by elhachi** [comment]
> > > Did you reset the `mint` repository to the provided commit?
> > > ```
> > > $ cd ~/go/src/github.com/bifurcation/mint
> > > $ git reset --hard a6080d464fb57a9330c2124ffb62f3c233e3400e
> > > # Check that no more build issues arise
> > > $ cd ~/go/src/github.com/lucas-clemente/quic-go
> > > $ go build
> > > # This should not produce any output
> > > ```
> > 
> > 
> > I have done this but I still get the same error KeyLen and IvLen undefined
> 
> Yea you have to reset ALL repos that produce errors. I reset all packages to ~December 2017 and it fixed it.

I'm new to golang and I got really hard time because of this error. I tried to update th golang version, reset the mint repo, use the oldest version of quic-go (I guessed that the error appears because of using different version of the mpquic (go1.9) and the quic-go (go1.17))... but nothing solved the problem... @cat24max Could you please tell me, in more details, how you fixed it ?

**Comment by Prakash-Sanchela** [comment]
> > > > Did you reset the `mint` repository to the provided commit?
> > > > ```
> > > > $ cd ~/go/src/github.com/bifurcation/mint
> > > > $ git reset --hard a6080d464fb57a9330c2124ffb62f3c233e3400e
> > > > # Check that no more build issues arise
> > > > $ cd ~/go/src/github.com/lucas-clemente/quic-go
> > > > $ go build
> > > > # This should not produce any output
> > > > ```
> > > 
> > > 
> > > I have done this but I still get the same error KeyLen and IvLen undefined
> > 
> > 
> > Yea you have to reset ALL repos that produce errors. I reset all packages to ~December 2017 and it fixed it.
> 
> I'm new to golang and I got really hard time because of this error. I tried to update th golang version, reset the mint repo, use the oldest version of quic-go (I guessed that the error appears because of using different version of the mpquic (go1.9) and the quic-go (go1.17))... but nothing solved the problem... @cat24max Could you please tell me, in more details, how you fixed it ?

Even after resetting the 

> /bifurcation/mint 

repository, I am still facing the same issue.

**Comment by Yessir-kim** [comment]
I have the same issue after ressetting the '/bifurcation/mint' repos, but it is working now.  (go version 1.20) 

I've had success with this: 

1. remove the 'github.com/bifurcation/mint' line in your go.mod (in github.com/lucas-clemente/quic-go)
2. type the command 'go get github.com/bifurcation/mint@a6080d464fb57a9330c2124ffb62f3c233e3400e' 
3. and then 'go build'

When you just use 'go get' except for the version, I guess it always download lastest version of mint. (that doesn't have KeyLen and IvLen fields)

So, You have to specify the version to use indirect version.

**Comment by Prakash-Sanchela** [comment]
> I have the same issue after ressetting the '/bifurcation/mint' repos, but it is working now. (go version 1.20)
> 
> I've had success with this:
> 
> 1. remove the 'github.com/bifurcation/mint' line in your go.mod (in github.com/lucas-clemente/quic-go)
> 2. type the command 'go get github.com/bifurcation/mint@a6080d464fb57a9330c2124ffb62f3c233e3400e'
> 3. and then 'go build'
> 
> When you just use 'go get' except for the version, I guess it always download lastest version of mint. (that doesn't have KeyLen and IvLen fields)
> 
> So, You have to specify the version to use indirect version.

Thanks @Yessir-kim . Worked for me. That perticular module for the commit got added into $GOPATH/pkg/mod path
